name: Dev Deployment

on:
  push:
    branches:
      - dev

jobs:
  Test:
    uses: ./.github/workflows/reusable_test.yml
    with:
      stage: dev
  Deploy:
    needs: Test
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      stage: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_SECRET_ACCESS_KEY }}
