name: Production Pipeline

on:
  push:
    branches:
      - prod

jobs:
  Production-Deployment:
    uses: ./.github/workflows/reusable_workflow.yml
    with:
      stage: prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.PROD_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_SECRET_ACCESS_KEY }}
